### PR TITLE
Escape regex special characters in the completion mode

### PR DESCRIPTION
**Pull request by melgenek**
This pr updates the autocompletion logic for the regex special characters.
Currently, the issues lead to cryptic errors like
```
Error: query is expected to fail with error:
	DataFusion error: Error during planning: arrow_cast requires its second argument to be a constant string, got Int64(43)
but got error:
	DataFusion error: Error during planning: arrow_cast requires its second argument to be a constant string, got Int64(43)
[SQL] SELECT arrow_cast('1', 43)
at tests/sqllogictests/test_files/arrow_typeof.slt:98
```

The problem is that the autocompletion mode added the plain brachets `()` in the example above. And it should've escaped the brackets with `\(\)`. Otherwise, they are treated as a regex group.

For more details about the issue, please, see https://github.com/apache/arrow-datafusion/issues/5727

### CODE REVIEW

**Review by xxchan — APPROVED** [review]
🤣 LGTM. Thanks! 

Could you please help update the version and the changelog? Then I can publish a patch for you.

**Comment by melgenek** [comment]
> Could you please help update the version and the changelog? Then I can publish a patch for you.

Should I do this in a separate pr? Or can I update this one?

**Comment by xxchan** [comment]
published

**Comment by melgenek** [comment]
Thank you!

**Comment by alamb** [comment]
> Could you please help update the version and the changelog? Then I can publish a patch for you. 

Wow -- thank you both so much!

**Comment by alamb** [comment]
For the record, I think https://crates.io/crates/sqllogictest/0.13.2 contains the fix

**Pull request merged**
