### PR TITLE
feat: support hook function after query

### PR DESCRIPTION
**Pull request by wangrunji0408**
This PR allows users to add hook functions after each query or statement completes.
For example, to test fault recovery, I'd like to kill nodes and wait for a while between queries. In this case I can register a custom function using these API.

### CODE REVIEW

**Review by xxchan — COMMENTED** [review]
> For example, to test fault recovery, I'd like to kill nodes and wait for a while between queries. In this case I can register a custom function using these API.

Can you elaborate a bit more about how to use it? What hook will you register? 🤔

**Comment by wangrunji0408** [comment]
> Can you elaborate a bit more about how to use it? What hook will you register? 🤔

Something like this one:
https://github.com/singularity-data/risingwave/blob/eb23ae236aa512277c1f3a66da5334c7e53f23c6/src/tests/simulation/src/main.rs#L158-L166

**Review by xxchan — APPROVED** [review]
> Something like this one:
[singularity-data/risingwave@eb23ae2/src/tests/simulation/src/main.rs#L158-L166](https://github.com/singularity-data/risingwave/blob/eb23ae236aa512277c1f3a66da5334c7e53f23c6/src/tests/simulation/src/main.rs#L158-L166)

This makes some sense. But I'm wondering whether there are any other possible meaningful hooks, because IMHO it's uncommon to run a parameterless function after each query 🤪

**Comment by xxchan** [comment]
Is `on_query_complete` already represented by `validator`? 🤔

**Comment by wangrunji0408** [comment]
>  But I'm wondering whether there are any other possible meaningful hooks, because IMHO it's uncommon to run a parameterless function after each query 🤪

Yes, it makes more sense to pass the query as a parameter. 🤣

> Is `on_query_complete` already represented by `validator`?

They are executed at adjacent locations, but with different functionality. So they should not be mixed up.

**Pull request merged**
