### PR TITLE
feat: new test ui

### PR DESCRIPTION
**Pull request by skyzh**
Signed-off-by: Alex Chi <iskyzh@gmail.com>

image

close https://github.com/risinglightdb/sqllogictest-rs/issues/19

### CODE REVIEW

**Comment by skyzh** [comment]
... on error:

image

**Review by st1page — APPROVED** [review]
LGTM

**Comment by skyzh** [comment]
cc @BugenZhao would you please also take a look? Thanks!

**Comment by BugenZhao** [comment]
> cc @BugenZhao would you please also take a look? Thanks!

This is cool! LGTM.

**Pull request merged**
